{
 "title": "METRICS",
 "time": { "from": "2020-07-25T07:39:17.321Z", "to": "2020-07-25T08:00:33.410Z" },
 "panels": [
  {
   "title": "Alive nodes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "master_node_alive_nodes" }
   ]
  },
  {
   "title": "Encryption request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "master_node_encryption_requestCount_total"
    }
   ]
  },
  {
   "title": "Encryption Processing Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "master_node_encryptionTime_seconds_count"
    }
   ]
  },
  {
   "title": "Decryption request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "master_node_decryption_requestCount_total"
    },
    {
     "expr": "master_node_decryption_successCount_total"
    },
    {
     "expr": "master_node:decryption_failure:count"
    }
   ]
  },
  {
   "title": "Instance encryption time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "encryption_node_encryptionTime_seconds_count"
    }
   ]
  },
  {
   "title": "Decryption processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "master_node_decryptionTime_seconds_count"
    }
   ]
  },
  {
   "title": "Instance decryption time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "encryption_node_decryptionTime_seconds_count"
    },
    {}
   ]
  }
 ]
}